=== 19longdt/FPT-University/Web Development (XML)/Practice_DTD/public_html/ex2.dtd
<?xml version='1.0' encoding='UTF-8'?>


<!--- Put your DTDDoc comment here. -->
<!ELEMENT bank (account*,customer*,depositor*)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT account ANY>
<!ATTLIST account
    account-number CDATA #REQUIRED
    branch-name CDATA #REQUIRED
    balance CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT customer ANY>
<!ATTLIST customer
    customer-name CDATA #REQUIRED
    customer-street CDATA #REQUIRED
    customer-city CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT depositor ANY>
<!ATTLIST depositor
    account-number CDATA #REQUIRED
    customer-name CDATA #REQUIRED
  >

=== 19longdt/FPT-University/Web Development (XML)/Practice_DTD/public_html/ex2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE bank SYSTEM "ex2.dtd">

<bank>
    <account account-number="A-101" branch-name="Downtown" balance="500">
    </account>
    
    <account account-number="A-102" branch-name="Perryridge" balance="400">
    </account>
    
    <account account-number="A-201" branch-name="Brighton" balance="900">
    </account>
    
    <customer customer-name="Johnson" customer-street="Alma" customer-city="Palo Alto">
    </customer>
    
    <customer customer-name="Hayes" customer-street="Main" customer-city="Harrison">
    </customer>
    
    <depositor account-number="A-101" customer-name="Johnson"></depositor>
    
    <depositor account-number="A-201" customer-name="Johnson"></depositor>
    
    <depositor account-number="A-102" customer-name="Hayes"></depositor>
</bank>
