=== 19longdt/FPT-University/Web Development (XML)/Practice_DTD/public_html/store.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Stores (Store)+>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Store (products)*>
<!ATTLIST Store
    sid ID #REQUIRED
    name CDATA #REQUIRED
    phone CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT products (product)+>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT product (name,price,description,sell?)>
<!ATTLIST product
    pid CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT price (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT description (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sell (#PCDATA)>

=== 19longdt/FPT-University/Web Development (XML)/Practice_DTD/public_html/ex1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE Stores SYSTEM "store.dtd">

<Stores>
    <Store sid="s282" name="Wiz" phone="555-1234">
        <products>
            <product pid="233">
                <name>gizmo plus</name>
                <price>99.99</price>
                <description>more</description>
                <sell>25%</sell>
            </product>
        </products>
    </Store>
    <Store sid="s521" name="Econo-Wiz" phone="555-6543">
        <products>
            <product pid="323">
                <name>gizmo</name>
                <price>22.99</price>
                <description>great</description>
                <sell>10%</sell>
            </product>
            <product pid="233">
                <name>gadget</name>
                <price>99.99</price>
                <description>more</description>
                <sell>15%</sell>
            </product>
        </products>
    </Store>    
</Stores>
