=== 19longdt/FPT-University/Web Development (XML)/Practice_Schema/public_html/stores.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="stores" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="store" minOccurs="1" maxOccurs="10">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="store_name"></xs:element>
                            <xs:element name="address"></xs:element>
                            <xs:element name="phone">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{10,11}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="item" minOccurs="3" maxOccurs="100">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="item_name"></xs:element>
                                        <xs:element name="count">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="1"></xs:minInclusive>
                                                    <xs:maxInclusive value="200"></xs:maxInclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        
                                        <xs:element name="sale">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="sale|normal"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        
                                        <xs:element name="price">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:float">
                                                    <xs:minExclusive value="0"></xs:minExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="code">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[A-Z]{2}[0-9]{2}"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                                
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== 19longdt/FPT-University/Web Development (XML)/Practice_Schema/public_html/store.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<stores
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='stores.xsd'>
    <store>
        <store_name>NAme</store_name>
        <address>Hanoi</address>
        <phone>12345678912</phone>
        <item code="HA12">
            <item_name>a</item_name>
            <count>12</count>
            <sale>sale</sale>
            <price>12</price>
        </item>
        <item code="HA12">
            <item_name>a</item_name>
            <count>12</count>
            <sale>sale</sale>
            <price>12</price>
        </item>
        <item code="HA12">
            <item_name>a</item_name>
            <count>12</count>
            <sale>sale</sale>
            <price>12</price>
        </item>
    </store>

</stores>
