=== 19longdt/FPT-University/Web Development (XML)/IS1419_HE141276_XmlAssignment1/public_html/Horse.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!--    <xs:simpleType name="valid_date">
        <xs:restriction base="xs:string">
            <xs:pattern value="^[1-9]{1}\d{3}-[0-1]{1}\d{1}-[0-3]{1}\d{1}$"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>-->
    <xs:simpleType name="valid_gender">
        <xs:restriction base="xs:string">
            <xs:pattern value="([F]?[M]?){1}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="Race">
        <xs:complexType>
            <xs:sequence>
                <xs:element name ="Course" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CourseName" type="xs:string"></xs:element>
                            <xs:element name="Address" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Horses">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name ="Horse" minOccurs="1" maxOccurs="3">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Value" type="xs:positiveInteger"></xs:element>
                                        <xs:element name="DateOfBirth" type="xs:date"></xs:element>
                                        <xs:element name="Gender" type="valid_gender"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="Name" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    
                </xs:element>
                
            </xs:sequence>
            
            <xs:attribute name="date" type="xs:date" use="required"></xs:attribute>
            <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 19longdt/FPT-University/Web Development (XML)/IS1419_HE141276_XmlAssignment1/public_html/Horse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->
<?xml-stylesheet type="text/css" href="Horse.css"?>
<?xml-stylesheet type="text/xml" href="Horse.xsl"?>

<Race date="2010-12-31" name ="New Years Meet"
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Horse.xsd'>
    <Course>
        <CourseName>The new track</CourseName>
        <Address>Track Road 123</Address>
    </Course>
    <Horses>
        <Horse Name="Bonfire">
            <Value>5000</Value>
            <DateOfBirth>1988-01-02</DateOfBirth>
            <Gender>M</Gender>
        </Horse>
        <Horse Name="Faithfull Dobbin">
            <Value>3500</Value>
            <DateOfBirth>1986-05-31</DateOfBirth>
            <Gender>F</Gender>
        </Horse>
        <Horse Name="Prgasus">
            <Value>3000</Value>
            <DateOfBirth>1992-06-23</DateOfBirth>
            <Gender>M</Gender>
        </Horse>
    </Horses>
</Race>

=== 19longdt/FPT-University/Web Development (XML)/IS1419_HE141276_XmlAssignment1/horse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<Race
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='public_html/Horse.xsd'>
    <Course>
        <CourseName></CourseName>
        <Address></Address>
    </Course>
    <Horse Name="">
        <Value></Value>
        <DateOfBirth></DateOfBirth>
        <Gender></Gender>
    </Horse>

</Race>
